### ISSUE TITLE
add License

### ISSUE THREAD

**Issue by matteofigus** [debopamsengupta/requirey#1]
I think we would be interested about using this in https://github.com/opentable/oc but we would need to ensure we have a compatible license for it. We go MIT for all the oc related stuff, would MIT be good for you too here? I can do a PR for that if you want

**Comment by debopamsengupta** [comment]
Sounds good :) a PR would be great

**Comment by debopamsengupta** [comment]
added the MIT license, so should be good for use. Please let me know if you'd like to see anything else there

**Comment by matteofigus** [comment]
Sorry, was meant to make a PR and got lost in the backlog :) Thanks
