### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by matteofigus** [debopamsengupta/requirey#2]
For integrating requirey to https://github.com/opentable/oc we would need to ensure the tests run on windows too. For OC, we use appveyor, which is free for open source, and allows to run all the tests in a windows platform too. Would you be in favour of integrating something like that here too?

**Comment by debopamsengupta** [comment]
Sure, I'll add the appveyor tests to ensure windows support :)

**Comment by debopamsengupta** [comment]
added the appveyor tests https://github.com/debopamsengupta/requirey/blob/master/appveyor.yml
