### ISSUE TITLE
Question: install automatically skips the install if dep already installed?

### ISSUE THREAD

**Issue by matteofigus** [debopamsengupta/requirey#5]
The main reason I ask, is that I know npm by default, is able to perform a quicker operation during npm install if the dep is already installed.

Is requirey able to do the same?

The reason I ask, is I would like to use requirey for OC. I think the integration there will include a step, during the registry start, to install the deps, but I also think we'll develop a step to perform a install separately (as a post npm install step for your registry app) - so that the install step should just be quick and the registry able to start quicker (useful for when developing multiple instances with a docker container that already contains the installed dependencies).

**Comment by debopamsengupta** [comment]
@matteofigus yep, if the `dependency@version` is already installed, requirey won't re-install again 😄

**Comment by matteofigus** [comment]
ok, closing so :)
