### ISSUE TITLE
Allow config to have both "module" or [modules]

### ISSUE THREAD

**Issue by matteofigus** [debopamsengupta/requirey#6]
We would like to use this module both for a config that supports for each module an array or a specific version (for both "classic" installs or "multi" installs).

Example:
```js
const ry = require('requirey')({ lodash: '3.4.5' });
const ry2 = require('requirey')({ lodash: ['1.2.3', '4.5.6'] });

ry.installAll();
ry2.installAll();

const l3 = require('lodash');
const l1 = ry2.require('lodash@1');
const l4 = ry2.require('lodash@4');
```

If it's ok, we can make a PR

**Comment by debopamsengupta** [comment]
Hi @matteofigus sounds fine, just a question though..any particular reason why a specific version can't be an array of 1 element ?

**Comment by matteofigus** [comment]
I think the main thing is we want to use it with new features. One of them will be to use this from a module, where we'll just parse its package.json, and possibly bring to ry's init the "dependencies" whole object without being in need to parse it and remap the object to have deps with an array of 1 element.

**Comment by debopamsengupta** [comment]
right :) a PR would be great !
