### ISSUE TITLE
Make installs and requires stricter

### ISSUE THREAD

**Issue by debopamsengupta** [debopamsengupta/requirey#8]
Right now, it is possible to initialize `requirey` with an empty config like 
```js
const ry = require('requirey')();
```
and install any module
```js
ry.install('react') //will install react@latest
```

also, it's possible to force a require call to a version like
```js
new ry.Requirer().require('react', 'latest', true) //using the {force} param
```
It might be a good idea to have a `strict` mode where all installs and requires must follow the initial `config` which becomes the single source of truth

**Comment by debopamsengupta** [comment]
cc @matteofigus @vanclevstik

**Comment by vanclevstik** [comment]
Yep, I think that should actually be the default behaviour, to keep all the configuration in one place and ensure we don't install random versions in multiple places

**Comment by debopamsengupta** [comment]
done with #9
